### ISSUE TITLE
TypeError when using --reporter xunit 

### ISSUE THREAD

**Issue by peteroreil** [mmotkina/mocha-parallel-tests#31]
when executing multiple suites and using xunit reporter a Type error is thrown.
```
./node_modules/.bin/mocha-parallel-tests ./test/integration/*.js --reporter xunit
```
results in 
```
TypeError: Cannot read property 'reporterOptions' of undefined
    at new XUnit (/home/peter/repos/historical-aggregator/node_modules/mocha/lib/reporters/xunit.js:44:14)
    at customRunner.on.reporter (/home/peter/repos/historical-aggregator/node_modules/mocha-parallel-tests/dist/lib/reporter.js:88:20)
```

the xunit constructor requires an options parameter 
```javascript
/**
 * Initialize a new `XUnit` reporter.
 *
 * @api public
 * @param {Runner} runner
 */
function XUnit(runner, options) {
  Base.call(this, runner);

  var stats = this.stats;
  var tests = [];
  var self = this;

  if (options.reporterOptions && options.reporterOptions.output) {
    if (!fs.createWriteStream) {
      throw new Error('file output not supported in browser');
    }

```

However the mocha-parallel-reporter in setUserReporter 
(./dist/lib/reporter.js) is only passing a single parameter.

```javascript
const setUserReporter = reporter => {
    try {
        UserReporter = require(`mocha/lib/reporters/${ reporter }`);
    } catch (evt) {
        try {
            UserReporter = require(reporter);
        } catch (evt) {
            // console.log('Please use existing reporter');
            return;
        }
    }

    UserReporter = new UserReporter(customRunner);
};
```

I updated the UserReporter constructor to pass an empty object in the constructor. 
It fixed my issues with xunit and didn't seem to effect default spec reporter, however unsure of how it may effect other reporters.

Peter 
:+1:

**Comment by 1999** [comment]
@peteroreil thanks for posting this issue. PR is merged and the new version is being published.
