### ISSUE TITLE
mpt exits without any error when some test throws error on start

### ISSUE THREAD

**Issue by megatolya** [mmotkina/mocha-parallel-tests#48]
I had missing deps in my app. I launched `mocha-parallel-tests` and it logged nothing. If i run same tests with `mocha` it shows stack trace (in my case it shows that module not found). 

```
[18:27:40][Step 2/2] > kinopoisk-mobile-www@1.0.0 test:integration /var/lib/teamcity/BuildAgents/teamcity-agent01i.media.yandex.net/work/890e4d2593f3cd9f
[18:27:40][Step 2/2] > mocha-parallel-tests --retry 1 --max-parallel 10 --reporter=$REPORTER --timeout 10000 --slow 100 test/integration/tests/*
[18:27:40][Step 2/2] 
[18:27:41][Step 2/2] Tue, 26 Jul 2016 15:27:41 GMT mocha-parallel-tests Run mocha test: ../../../../../test/integration/tests/KINOFRONT-7799_test-of-tests/index.js
[18:27:41][Step 2/2] Tue, 26 Jul 2016 15:27:41 GMT mocha-parallel-tests suite event fired (../../../../../test/integration/tests/KINOFRONT-7799_test-of-tests/index.js)
[18:27:41][Step 2/2] Tue, 26 Jul 2016 15:27:41 GMT mocha-parallel-tests Chose test file from queue: ../../../../../test/integration/tests/KINOFRONT-7799_test-of-tests/index.js
[18:27:41][Step 2/2] Tue, 26 Jul 2016 15:27:41 GMT mocha-parallel-tests Run mocha test: ../../../../../test/integration/tests/KINOFRONT-7799_test-of-tests/server.js
```

VS

```
[18:46:56][Step 2/2] module.js:442
[18:46:56][Step 2/2]     throw err;
[18:46:56][Step 2/2]     ^
[18:46:56][Step 2/2] 
[18:46:56][Step 2/2] Error: Cannot find module 'express-conditions'
[18:46:56][Step 2/2]     at Function.Module._resolveFilename (module.js:440:15)
[18:46:56][Step 2/2]     at Function.Module._load (module.js:388:25)
[18:46:56][Step 2/2]     at Module.require (module.js:468:17)
[18:46:56][Step 2/2]     at require (internal/module.js:20:19)
[18:46:56][Step 2/2]     at Object.<anonymous> (/var/lib/teamcity/BuildAgents/teamcity-agent02f.media.yandex.net/work/890e4d2593f3cd9f/test/integration/tests/KINOFRONT-7799_test-of-tests/server.js:2:17)
[18:46:56][Step 2/2]     at Module._compile (module.js:541:32)
[18:46:56][Step 2/2]     at Object.Module._extensions..js (module.js:550:10)
[18:46:56][Step 2/2]     at Module.load (module.js:458:32)
[18:46:56][Step 2/2]     at tryModuleLoad (module.js:417:12)
[18:46:56][Step 2/2]     at Function.Module._load (module.js:409:3)
[18:46:56][Step 2/2]     at Module.require (module.js:468:17)
[18:46:56][Step 2/2]     at require (internal/module.js:20:19)
[18:46:56][Step 2/2]     at /var/lib/teamcity/BuildAgents/teamcity-agent02f.media.yandex.net/work/890e4d2593f3cd9f/node_modules/mocha/lib/mocha.js:220:27
[18:46:56][Step 2/2]     at Array.forEach (native)
[18:46:56][Step 2/2]     at Mocha.loadFiles (/var/lib/teamcity/BuildAgents/teamcity-agent02f.media.yandex.net/work/890e4d2593f3cd9f/node_modules/mocha/lib/mocha.js:217:14)
[18:46:56][Step 2/2]     at Mocha.run (/var/lib/teamcity/BuildAgents/teamcity-agent02f.media.yandex.net/work/890e4d2593f3cd9f/node_modules/mocha/lib/mocha.js:469:10)
[18:46:56][Step 2/2]     at Object.<anonymous> (/var/lib/teamcity/BuildAgents/teamcity-agent02f.media.yandex.net/work/890e4d2593f3cd9f/node_modules/mocha/bin/_mocha:404:18)
[18:46:56][Step 2/2]     at Module._compile (module.js:541:32)
[18:46:56][Step 2/2]     at Object.Module._extensions..js (module.js:550:10)
[18:46:56][Step 2/2]     at Module.load (module.js:458:32)
[18:46:56][Step 2/2]     at tryModuleLoad (module.js:417:12)
[18:46:56][Step 2/2]     at Function.Module._load (module.js:409:3)
[18:46:56][Step 2/2]     at Module.runMain (module.js:575:10)
[18:46:56][Step 2/2]     at run (bootstrap_node.js:352:7)
[18:46:56][Step 2/2]     at startup (bootstrap_node.js:144:9)
[18:46:56][Step 2/2]     at bootstrap_node.js:467:3
```

**Comment by 1999** [comment]
Толик, кажется это просто какие-то настройки репортера или что-то типа того. Во всяком случае тест стабильно валится:

```
77:mocha-parallel-tests dsorin$ mocha test/missing-dependency/

  Test suite
    1) should end now


  0 passing (12ms)
  1 failing

  1) Test suite should end now:
     Error: Cannot find module 'missing-dependency-1469678938413'
      at require (internal/module.js:12:17)
      at Context.<anonymous> (test/missing-dependency/test.js:5:20)



77:mocha-parallel-tests dsorin$ git 
77:mocha-parallel-tests dsorin$ dist/bin/mocha-parallel-tests test/missing-dependency/test.js
test/mocha.opts


  Test suite
    1) should end now


  0 passing (24ms)
  1 failing

  1) Test suite should end now:
     Error: Cannot find module 'missing-dependency-1469678956178'
      at require (internal/module.js:12:17)
      at Context.<anonymous> (test/missing-dependency/test.js:5:20)



77:mocha-parallel-tests dsorin$ echo $?
1
```

Покажи мне вживую.

**Comment by megatolya** [comment]
воспроизвел вот так, с синтаксической ошибкой под 4ой нодой:
```
$ DEBUG="mocha-parallel-tests" PULL_REQUEST=14 ./node_modules/.bin/mocha --retry 1 --max-parallel 10 --timeout 10000 --slow 100 test/integration/tests/*

/home/megatolya/www/mobile/test/integration/tests/KINOFRONT-7799_test-of-tests/server.js:4
module.exports = ({iosApi: app}) => {
                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/megatolya/www/mobile/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/megatolya/www/mobile/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/megatolya/www/mobile/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/megatolya/www/mobile/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by megatolya** [comment]
локально кстати тоже воспроизводится по четвертой нодой, под шестой ок

**Comment by 1999** [comment]
Посмотри тест плз? https://github.com/mmotkina/mocha-parallel-tests/pull/50/files
Я или смотрю не туда, или не так тебя понял. У меня на 4 ноде mpt падает с ошибкой как и ожидается

**Comment by megatolya** [comment]
да, такой же делал и тоже не воспроизвелось. Хотя на деве все еще воспроизводится. попробую на досуге понять, в чем разница

**Comment by 1999** [comment]
Кажись это тот самый error outside test suite, который давно ловил @k03mad:
```
$ PULL_REQUEST=14 mocha-parallel-tests test/integration/tests/* 


  1) Uncaught error outside test suite
  KINOFRONT-7799: Новый подход к тестам, моковый сервер
    ✓ Check movie title and tests it self (1918ms)

~/www/mobile develop
$ echo $?
0
```

**Comment by 1999** [comment]
Для памяти скопирую решение сюда. Все еще падают несколько тестов:
```
diff --git index.js index.js
index 6333e54..2d6aef1 100644
--- index.js
+++ index.js
@@ -45,6 +45,26 @@ export default function MochaParallelTests(options) {
         retryCount: options.retry
     });
 
+    const hooks = [
+        'afterEach',
+        'after',
+        'beforeEach',
+        'before',
+        'describe',
+        'it',
+        'setup',
+        'suiteSetup',
+        'suiteTeardown',
+        'suite',
+        'teardown',
+        'test',
+        'run'
+    ];
+
+    for (let hook of hooks) {
+        global[hook] = () => {};
+    }
+
     files.forEach(file => {
         const testOptions = Object.assign({}, options, {
             reporterName: options.R || options.reporter,
@@ -52,8 +72,17 @@ export default function MochaParallelTests(options) {
             testsLength: files.length
         });
 
-        addTest(path.resolve(file), testOptions);
+        // does this file have a syntax error?
+        const absFilePath = path.resolve(file);
+        require(absFilePath);
+        delete require.cache[absFilePath];
+
+        addTest(absFilePath, testOptions);
     });
 
+    for (let hook of hooks) {
+        delete global[hook];
+    }
+
     runTests();
 }
```

**Comment by 1999** [comment]
Решу вопрос в #54 и опубликую версию 0.5.6
