### ISSUE TITLE
Using mocha-parallel-tests programmatically

### ISSUE THREAD

**Issue by mattrlong** [mmotkina/mocha-parallel-tests#58]
In the project that Im working on current Mocha is used [programmatically](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically), rather than it being initialised from a make or grunt file.

When I've attempted to update to helper functions to use mocha-parallel-tests rather than mocha, i've simply tried to replace the require statement from: 
var Mocha = require('mocha') to var Mocha = require('mocha-parallel-tests'), and left my programatic configuration as is:

	var mocha = new Mocha({
		ui: 'bdd',
		reporter: 'mocha-jenkins-reporter',
		reporterOptions: {
			junit_report_name: "Test Report",
			junit_report_path: "./reports/functionalTests.xml",
			junit_report_stack: 1
		},
		timeout: 60000
	});

However, I have an ES6 problem when this library is required:
/.../src/node_modules/mocha-parallel-tests/index.js:3
import path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../src/test/parallel/test-helper.js:3:13)
    at Module._compile (module.js:541:32)

Do you have any recommendations for programatic configuration?

**Comment by 1999** [comment]
Hm, seems like you're either using an old mocha-parallel-tests version or installed it via `git://`. How do you include mocha-parallel-tests into your project?

**Comment by mattrlong** [comment]
Thanks for the quick reply. 

I've installed it using the npm commands listed on the readme.

**Comment by 1999** [comment]
Seems strange. I will investigate into this issue asap. Thanks for the issue.

**Comment by 1999** [comment]
Please try mocha-parallel-tests@1.1.1

**Comment by mattrlong** [comment]
Hi thanks for the quick fix. It's resolved the original issue, however when we're adding the spec files programmatically, we are using mocha's addFile function, which doesn't appear to be supported in mocha-parallel-tests. 

TypeError: mocha.addFile is not a function
    at Object.mochaFactory (/.../src/test/parallel/test-helper.js:135:9)
    at Object.TestRunner.runMochaOnFileSet (/.../src/test.js:150:26)
    at Object.<anonymous> (/.../src/test.js:289:9)
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by 1999** [comment]
Eh... another example that any change should have been covered with tests :(
Thanks, will fix that today.

**Comment by 1999** [comment]
@mattrlong could you please try `1.2.0-beta.2` version? Is it working as expected?

**Comment by mattrlong** [comment]
@1999 I'm now seeing this error when calling run() 

(node) warning: possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at Runner.run (/.../src/node_modules/mocha/lib/runner.js:815:11)
    at Mocha.run (/.../src/node_modules/mocha/lib/mocha.js:519:17)
    at fileRunners.forEach (/.../src/node_modules/mocha-parallel-tests/dist/lib/watcher.js:236:30)
    at streams.forEach.fileRunners.forEach (/.../src/node_modules/mocha-parallel-tests/dist/lib/watcher.js:299:29)
    at streams.forEach.exports.runTests._runner2.default.on (/.../src/node_modules/mocha-parallel-tests/dist/lib/watcher.js:336:5)
    at MochaParallelTests.run (/.../src/node_modules/mocha-parallel-tests/dist/api.js:61:31)
    at Object.TestRunner.runMochaOnFileSet (/.../src/test.js:232:29)
    at Object.<anonymous> (/.../src/test.js:290:9)
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by mattrlong** [comment]
I may also be running into https://github.com/mmotkina/mocha-parallel-tests/issues/47 as I'm using the selenium test wrapper too.

**Comment by 1999** [comment]
Can you give me an example so I could try this myself?

**Comment by mattrlong** [comment]
@1999 I think this is the snippet you're after. (I've cut and paste the relevant pieces out of our codebase, so some of the dependencies might be missing, but hopefully enough)

Mocha = require('mocha-parallel-tests');

var TestRunner = function (options) {
	this.options = options;
};

TestRunner.prototype = {

	runMochaOnFileSet: function (paths, cb) {
		var maxThreads = config.has('selenium.maxParallel') ? config.get('selenium.maxParallel') : 1;
		var mocha = mochaFactory(paths, maxThreads);

		console.log('single mode');
		console.log('Single startTime:', Date.now());
		console.time('single');

		var singleRunner = mocha.run(function (failures) {
			console.log('Single endTime:', Date.now());
			console.timeEnd('single');
			cb(failures);
		});
		singleRunner.on('fail', function (test, err) {
			console.log('Single fail:', Date.now());
			console.log('err.stack\n\n', err.stack);
		});

	}
};

var mochaFactory = function (paths, maxParallel) {
	var mocha = new Mocha({
		ui: 'bdd',
		reporter: 'mocha-jenkins-reporter',
		reporterOptions: {
			junit_report_name: "Template Designer Functional Test Execution",
			junit_report_path: "functionalTests.xml",
			junit_report_stack: 1
		},
		timeout: 90000
		// maxParallel: maxParallel,
		// retry: 1
	});

	for (var i = 0; i < paths.length; i++) {
		console.log('Total number of spec files:', paths.length)
		mocha.addFile(paths[i]);
	}

	return mocha;
};

**Comment by 1999** [comment]
Please check 1.2.0-beta.3 version. Does it work for you? Do you see any selenium-webdriver errors during tests execution?

**Comment by mattrlong** [comment]
Hi thanks for the update. Im now no longer seeing the error that I was yesterday. However, due to #47 none of my tests will run as I'm instantiating my driver object in a test.before function. 

(A handful of my tests had incorrectly not been wrapped in the selenium 'test' functions, which highlighted the original issue)

**Comment by 1999** [comment]
Could you please post an example of your test which doesn't run at all? @mattrlong

**Comment by mattrlong** [comment]
Hi @1999,

Sure, this is similar to most of the specs I'm currently working with
```
test.describe('Top level describe ', function () {
	"use strict";

	var test = require('selenium-webdriver/testing');
	var webdriver = require('selenium-webdriver');

	test.before(function () {

		var driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();
	});

	test.describe('Sub describe - with selenium test wrapper', function () {
		test.it("Test with selenium test wrapper", function () {
			console.log("------- WITH ------- RUNS NOW");
			driver.get('http://www.google.com');
			assert.isTrue(true);
		});

		it("Test without wrapper", function () {
			console.log("------- WITHOUT ------- RUNS NOW");
			assert.isFalse(false);
		});
	});

	describe('Sub describe - without selenium test wrapper', function () {
		test.it("Test with selenium test wrapper", function () {
			console.log("------- WITH ------- RUNS NOW");
			driver.get('http://www.google.com');
			assert.isTrue(true);
		});

		it("Test without wrapper", function () {
			console.log("------- WITHOUT ------- RUNS NOW");
			assert.isFalse(false);
		});
	});
	
});
```

When executed you'll see a similar error to this:
 ReferenceError: driver is not defined
      at Context.<anonymous> (test/spec/.../demoTest.js:16:4)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at node_modules/selenium-webdriver/lib/promise.js:2820:25
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at run (node_modules/karma/node_modules/core-js/modules/es6.promise.js:89:22)
      at node_modules/karma/node_modules/core-js/modules/es6.promise.js:102:28
      at flush (node_modules/karma/node_modules/core-js/modules/_microtask.js:18:9)
  From: Task: Sub describe - with selenium test wrapper Test with selenium test wrapper
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

**Comment by mattrlong** [comment]
Apologies for the last comment, I spotted the unintentional mistake. I'd attempted to create a demostration of the issues I've been seeing, but in that separate demo.js the selenium test wrappers seem to be working. I'll try debugging what the issue is with our project configuration this afternoon and report back any issues.

**Comment by 1999** [comment]
No worries. If you see smth strange, post it right into #47

**Comment by mattrlong** [comment]
The cause of the issue is that a number of the files that are added to the Mocha object using addFile are actually base files & utilities files. To ensure that they are loaded before the specs, during standard Mocha execution, these files are 'unshifted' to the front of the paths array. Using Mocha-parallel-tests the hooks & global variables configured in these files are not being executed. 

The issue earlier today making me think I had a similar issue to #47 is that selenium-webdriver/testing var (test) is configured in the base file as a global throughout the project, hence none of the specs were being executed as the 'test' object is undefined. 

I'll look into options to require the base and utility files in each of the specs.

**Comment by 1999** [comment]
@mattrlong is `--require` option what you need?

**Comment by mattrlong** [comment]
Something like that, but due to the number of utilities files we have ideally something like --require-dir. Was planning to look into adding [this](https://www.npmjs.com/package/require-dir) to each of the specs with the directory of the utils. Obviously if it, or something similar could be incorporated into this repo that would be great
