### ISSUE TITLE
`describe.skip` is not a function

### ISSUE THREAD

**Issue by hpurmann** [mmotkina/mocha-parallel-tests#59]
This module fails executing the tests when skipping a top level describe block.

This minimal test
```javascript
import { expect } from 'chai'

describe.skip('describe block', () => {
  it('should ...', () => {
    expect(true).to.be.true
  })
})
```

gives me this output:

```
describe.skip('describe block', function () {
         ^

TypeError: describe.skip is not a function
    at Object.<anonymous> (foo.js:3:10)
    at Module._compile (module.js:541:32)
    at loader (/Users/myUser/myModule/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myUser/myModule/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at MochaParallelTests.files.forEach.file (/Users/myUser/myModule/node_modules/mocha-parallel-tests/dist/index.js:92:9)
```

**Comment by 1999** [comment]
Could you provide a bit more descriptive example of your test?

**Comment by hpurmann** [comment]
Sure. I updated the post.

**Comment by 1999** [comment]
Cool! Thanks for posting issue, will look at it tomorrow.

**Comment by hpurmann** [comment]
That was fast, thank you!

**Comment by 1999** [comment]
you're welcome!
