### ISSUE TITLE
"Uncaught error outside test suite"

### ISSUE THREAD

**Issue by thomas-huston-zocdoc** [mmotkina/mocha-parallel-tests#68]
After my first test suite runs, I always get "uncaught error outside test suite" and the process exits.

I added some logging inside Mocha itself to see what the stack trace was, and this is what I got:

```
TypeError: Cannot read property \'total\' of undefined
    at node_modules/mocha-parallel-tests/dist/lib/watcher.js:246:
19
    at Array.forEach (native)
    at fileRunners.forEach (node_modules/mocha-parallel-tests/dist/lib/watcher.js:240:17)
    at streams.forEach.fileRunners.forEach (node_modules/mocha-parallel-tests/dist/lib/watcher.js:299:29)
    at streams.forEach.exports.runTests._runner2.default.on (node_modules/mocha-pa
rallel-tests/dist/lib/watcher.js:336:5)
    at binHelper (node_modules/mocha-parallel-tests/dist/bin-helper.js:107:27)
    at Object.<anonymous> (node_modules/mocha-parallel-tests/dist/bin/mocha-parallel-tests:41:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:
32)
```

**Comment by 1999** [comment]
Hm... Could you please post an example of your test?

**Comment by 1999** [comment]
@thomas-huston-zocdoc ping
