### ISSUE TITLE
Mocha tap reporter throws exception

### ISSUE THREAD

**Issue by aubonpain** [mmotkina/mocha-parallel-tests#78]
**Issue:** Specifying "tap" as the reporter for mocha-parallel-tests throws a "TypeError: runner.grepTotal is not a function" error.

**Setup:**
Running selenium webdriver tests using Node, Mocha. Versions:
1. mocha-parallel-tests v1.2.2
2. mocha v3.0.2
3. node v6.6.0

**Command:** mocha-parallel-tests test/*.js --max-parallel 5 --slow 3000 --reporter tap
_Note:_ Using mocha (not mocha-parallel-tests), I can specify either "json", "tap", "spec", or any other reporter and the tests run fine. Additionally, mocha-parallel-tests can run "json" or "spec" as the reporter, but fails on using "tap".

**Stack:**
C:\Users\foo\AppData\Roaming\npm\node_modules\mocha\lib\reporters\tap.js:27
    var total = runner.grepTotal(runner.suite);
                       ^

TypeError: runner.grepTotal is not a function
    at Runner.<anonymous> (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha\lib\reporters\tap.js:27:24)
    at emitOne (events.js:101:20)
    at Runner.emit (events.js:188:7)
    at Runner.emit (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\runner.js:62:20)
    at Runner.start (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\runner.js:73:14)
    at new MochaParallelTests (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\reporter.js:128:26)
    at Mocha.run (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:491:18)
    at scheduleMochaRun (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\watcher.js:240:30)
    at runTestsRecursive (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\watcher.js:302:29)
    at exports.runTests._ref4 (C:\Users\foo\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\watcher.js:338:5)

Any help would be much appreciated!

**Comment by 1999** [comment]
Thank you for posting this issue. Will look at it asap.

**Comment by aubonpain** [comment]
@1999 Thanks, I'll be keeping a close eye on this. :) 

Also, what if I wanted to use another reporter, say mocha-jenkins-reporter? I tried to pass that in through mocha's --reporter option like so:
mocha-parallel-tests test\*.js --max-parallel 5 --reporter mocha-jenkins-reporter -O result.xml
But this didn't work with mocha-parallel-tests. It works fine with mocha, but not with mocha-parallel-tests. Any insight there would also be quite helpful.

**Comment by 1999** [comment]
@aubonpain from the first look it seems like mocha-jenkins-reporter works closely with runner inside reporter. If I'm not mistaken, this relates closely to current issue though it still would be useful if you create a separate one. In my PR #79 I'm trying to refactor runner to extend mocha runner object, not EventEmitter. Hopefully this will help.

**Comment by aubonpain** [comment]
@1999 Yes, I can see from the PR that the runner versions aren't the same for mocha and mocha-parallel-tests. Not sure I understand what you mean by "useful if you create a separate one" - happy to create another issue but can you please clarify?

**Comment by 1999** [comment]
Yes, I meant exactly this, sorry for being not clear. Hopefully the problem is the same for both this and jenkins-related issue.
